# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [3]:
%pip install pandas numpy scikit-learn matplotlib seaborn

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Collecting matplotlib
  Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl.metadata (80 kB)
Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\kahau\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.24.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl.metadata (121 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in C:\Users\kahau\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.2)
Collecting pillow>=9 (from matplotlib)
  Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in C:\Users\kahau\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   -------------------------------------- - 9.7/10.0 MB 87.5 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 46.4 MB/s  0:00:00
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------  12.3/12.6 MB 95.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 53.8 MB/s  0:00:00
Downloading scikit_learn-1.9.0-cp314-cp314-win_amd64.whl (8.3 MB)
   ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
   -------------------------------- ------- 6.8/8.3 MB 34.1 MB/s eta 0:00:01
   ---------------------------------------  8.1/8.3 MB 34.0 MB/s eta 0:00:01
   ---------------------------------------- 8.3/8.3 MB 14.8 MB/s  0:00:00
Downloading matplotlib-3.11.1-cp314-cp314-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 9.5/9.5 MB 51.0 MB/s  0:00:00
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl (232 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.63.0-cp314-cp314-win_amd64.whl (2.3 MB)
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl (75 kB)
Using cached narwhals-2.24.0-py3-none-any.whl (461 kB)
Downloading pillow-12.3.0-cp314-cp314-win_amd64.whl (7.2 MB)
   ---------------------------------------- 0.0/7.2 MB ? eta -:--:--
   ---------------------------------------- 7.2/7.2 MB 52.5 MB/s  0:00:00
Using cached pyparsing-3.3.2-py3-none-any.whl (122 kB)
Using cached scipy-1.18.0-cp314-cp314-win_amd64.whl (37.3 MB)
Downloading threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, threadpoolctl, pyparsing, pillow, numpy, narwhals, kiwisolver, joblib, fonttools, cycler, scipy, pandas, contourpy, scikit-learn, matplotlib, seaborn

   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----------------------------------------  0/16 [tzdata]
   ----- ----------------------------------  2/16 [pyparsing]
   ----- ----------------------------------  2/16 [pyparsing]
   ----- ----------------------------------  2/16 [pyparsing]
   ----- ----------------------------------  2/16 [pyparsing]
   ----- ----------------------------------  2/16 [pyparsing]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ------- --------------------------------  3/16 [pillow]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ---------- -----------------------------  4/16 [numpy]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ------------ ---------------------------  5/16 [narwhals]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   ----------------- ----------------------  7/16 [joblib]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   -------------------- -------------------  8/16 [fonttools]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]
   ------------------------- -------------- 10/16 [scipy]

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored
  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'C:\Users\kahau\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\kahau\AppData\Local\Python\pythoncore-3.14-64\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: C:\Users\kahau\AppData\Local\Python\pythoncore-3.14-64\python.exe -m pip install --upgrade pip

In [12]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [13]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [14]:
#your code here
spaceship.shape

(8693, 14)

**Check for data types**

In [15]:
#your code here
spaceship.dtypes

PassengerId         str
HomePlanet          str
CryoSleep        object
Cabin               str
Destination         str
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name                str
Transported        bool
dtype: object

**Check for missing values**

In [16]:
#your code here
spaceship.isnull().sum()

PassengerId       0
HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
Name            200
Transported       0
dtype: int64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [17]:
#your code here
spaceship_clean = spaceship.dropna().copy()

In [19]:
spaceship_clean.isnull().sum()

PassengerId     0
HomePlanet      0
CryoSleep       0
Cabin           0
Destination     0
Age             0
VIP             0
RoomService     0
FoodCourt       0
ShoppingMall    0
Spa             0
VRDeck          0
Name            0
Transported     0
dtype: int64

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [21]:
#your code here
spaceship_clean["Cabin"] = spaceship["Cabin"].str[0]

- Drop PassengerId and Name

In [23]:
#your code here
spaceship_clean = spaceship_clean.drop(
    columns=["PassengerId", "Name"]
)

- For non-numerical columns, do dummies.

In [24]:
#your code here
X = spaceship_clean.drop(columns=["Transported"])
y = spaceship_clean["Transported"]

In [25]:
X = pd.get_dummies(X, drop_first=True, dtype=int)

In [26]:
X.head()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Europa,HomePlanet_Mars,CryoSleep_True,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_True
0,39.0,0.0,0.0,0.0,0.0,0.0,1,0,0,1,0,0,0,0,0,0,0,1,0
1,24.0,109.0,9.0,25.0,549.0,44.0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,58.0,43.0,3576.0,0.0,6715.0,49.0,1,0,0,0,0,0,0,0,0,0,0,1,1
3,33.0,0.0,1283.0,371.0,3329.0,193.0,1,0,0,0,0,0,0,0,0,0,0,1,0
4,16.0,303.0,70.0,151.0,565.0,2.0,0,0,0,0,0,0,0,1,0,0,0,1,0

In [27]:
X.dtypes

Age                          float64
RoomService                  float64
FoodCourt                    float64
ShoppingMall                 float64
Spa                          float64
VRDeck                       float64
HomePlanet_Europa              int64
HomePlanet_Mars                int64
CryoSleep_True                 int64
Cabin_B                        int64
Cabin_C                        int64
Cabin_D                        int64
Cabin_E                        int64
Cabin_F                        int64
Cabin_G                        int64
Cabin_T                        int64
Destination_PSO J318.5-22      int64
Destination_TRAPPIST-1e        int64
VIP_True                       int64
dtype: object

**Perform Train Test Split**

In [28]:
#your code here
from sklearn.model_selection import train_test_split

X = spaceship_clean.select_dtypes(include="number")
y = spaceship_clean["Transported"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=0
)

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [29]:
#your code here
# Create the scaler
# Fit only on training data and transform it
# Train using the scaled training data
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier


scaler = MinMaxScaler()


X_train_scaled = scaler.fit_transform(X_train)


X_test_scaled = scaler.transform(X_test)


knn = KNeighborsClassifier(n_neighbors=5)


knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

- Evaluate your model's performance. Comment it

In [30]:
#your code here
accuracy = knn.score(X_test_scaled, y_test)

print(f"Accuracy: {accuracy:.2%}")

Accuracy: 74.43%

The K-Nearest Neighbors classifier achieved an accuracy of **74.43%** on the test data. This means that the model correctly predicted whether a passenger was transported for approximately three out of every four passengers. However, it still misclassified about **25.57%** of the test observations, so there is room for improvement. Further improvements could include testing different values of `neighbors`, selecting more useful features, or comparing KNN with other classification models.